=== Nekopawa/bsd-explorer/schemas/music.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/Nekopawa/bsd-explorer/main/schemas/music.schema.json",
    "title": "Music",
    "description": "Music used in different media throughout the BSD universe.",
    "type": "array",
    "items": {
        "type": "object",
        "description": "Music in a BSD media.",
        "properties": {
            "id": {
                "type": "string",
                "description": "The unique identifier of the song.",
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                "minLength": 1
            },
            "type": {
                "type": "string",
                "description": "The type of music used in the media.",
                "enum": [
                    "opening-theme",
                    "ending-theme",
                    "insert-song",
                    "theme-song",
                    "character-song"
                ]
            },
            "name": {
                "type": "string",
                "description": "The name of the song.",
                "minLength": 1
            },
            "artist": {
                "type": "string",
                "description": "The artist/band performing the song.",
                "minLength": 1
            },
            "lyricists": {
                "type": "array",
                "description": "The lyricists responsible for the song lyrics.",
                "items": {
                    "type": "string",
                    "description": "One of the lyricists responsible for the song lyrics.",
                    "minLength": 1
                },
                "minItems": 1
            },
            "composers": {
                "type": "array",
                "description": "The composers involved in the song composition.",
                "items": {
                    "type": "string",
                    "description": "One of the composers involved in the song composition.",
                    "minLength": 1
                },
                "minItems": 1
            },
            "releaseDate": {
                "type": "string",
                "description": "The release date of the song.",
                "format": "date",
                "minLength": 1
            },
            "startingEpisode": {
                "type": ["integer", "null"],
                "description": "The first episode of the anime in which the song is featured.",
                "minimum": 1
            },
            "endingEpisode": {
                "type": ["integer", "null"],
                "description": "The last episode of the anime in which the song is featured.",
                "minimum": 1
            },
            "openingNumber": {
                "type": ["integer", "null"],
                "description": "The number of the opening that features the song.",
                "minimum": 1
            },
            "endingNumber": {
                "type": ["integer", "null"],
                "description": "The number of the ending that features the song.",
                "minimum": 1
            },
            "songVideoLink": {
                "type": ["string", "null"],
                "description": "The link to the official video associated with the song.",
                "format": "uri",
                "minLength": 1
            },
            "fullSongLink": {
                "type": "string",
                "description": "The link of the original full video by the artist/band performing the song.",
                "format": "uri",
                "minLength": 1
            },
            "mediaId": {
                "type": "string",
                "description": "The ID of the media that features the song.",
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                "minLength": 1
            },
            "japaneseName": {
                "type": ["string", "null"],
                "description": "The name of the song in japanese.",
                "minLength": 1
            },
            "characterId": {
                "type": "string",
                "description": "The ID of the character that inspired the song.",
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                "minLength": 1
            }
        },
        "allOf": [
            {
                "if": {
                    "properties": {
                        "type": {
                            "const": "opening-theme"
                        }
                    },
                    "required": ["type"]
                },
                "then": {
                    "required": [
                        "artist",
                        "lyricists",
                        "composers",
                        "startingEpisode",
                        "endingEpisode",
                        "openingNumber",
                        "songVideoLink"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "const": "ending-theme"
                        }
                    },
                    "required": ["type"]
                },
                "then": {
                    "required": [
                        "artist",
                        "lyricists",
                        "composers",
                        "startingEpisode",
                        "endingEpisode",
                        "endingNumber",
                        "songVideoLink"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": ["insert-song", "theme-song"]
                        }
                    },
                    "required": ["type"]
                },
                "then": {
                    "required": [
                        "artist",
                        "lyricists",
                        "composers",
                        "songVideoLink"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "const": "character-song"
                        }
                    },
                    "required": ["type"]
                },
                "then": {
                    "required": ["artist", "composers", "characterId"]
                }
            }
        ],
        "required": ["id", "type", "name", "releaseDate", "fullSongLink"],
        "additionalProperties": false
    }
}

=== Nekopawa/bsd-explorer/src/data/music.json
[
    {
        "id": "deadly-drive",
        "type": "opening-theme",
        "name": "Deadly Drive",
        "artist": "GRANDRODEO",
        "lyricists": ["Kishō Taniyama"],
        "composers": ["Masaaki Iizuka"],
        "releaseDate": "2018-02-21",
        "startingEpisode": null,
        "endingEpisode": null,
        "openingNumber": null,
        "mediaId": "dead-apple-movie",
        "songVideoLink": "https://www.youtube.com/watch?v=sG_yxTzjxPA",
        "fullSongLink": "https://www.youtube.com/watch?v=iPXl0-6wJVE"
    },
    {
        "id": "reason-living",
        "type": "opening-theme",
        "name": "Reason Living",
        "artist": "SCREEN mode",
        "lyricists": ["Yōhei Matsui"],
        "composers": ["Masatomo Ōta"],
        "releaseDate": "2016-10-26",
        "startingEpisode": 13,
        "endingEpisode": 24,
        "openingNumber": 2,
        "songVideoLink": "https://www.youtube.com/watch?v=qrcDm4Pr3Ig",
        "fullSongLink": "https://www.youtube.com/watch?v=iEcOzINHOUE"
    },
    {
        "id": "setsuna-no-ai",
        "type": "opening-theme",
        "name": "Setsuna no Ai",
        "artist": "GRANRODEO",
        "lyricists": ["Kishō Taniyama"],
        "composers": ["Masaaki Iizuka"],
        "releaseDate": "2019-05-08",
        "startingEpisode": 26,
        "endingEpisode": 36,
        "openingNumber": 3,
        "songVideoLink": "https://www.youtube.com/watch?v=GCd2dc0LzfQ",
        "fullSongLink": "https://www.youtube.com/watch?v=bAOf9U4gEGo"
    },
    {
        "id": "tetsu-no-ori",
        "type": "opening-theme",
        "name": "Tetsu no Ori",
        "artist": "GRANRODEO",
        "lyricists": ["Kishō Taniyama"],
        "composers": ["Masaaki Iizuka"],
        "releaseDate": "2023-08-30",
        "startingEpisode": 51,
        "endingEpisode": 60,
        "openingNumber": 5,
        "songVideoLink": "https://www.youtube.com/watch?v=QvxSHPKXg94",
        "fullSongLink": "https://www.youtube.com/watch?v=1u9jsFZ0LUU"
    },
    {
        "id": "trash-candy",
        "type": "opening-theme",
        "name": "TRASH CANDY",
        "artist": "GRANRODEO",
        "lyricists": ["Kishō Taniyama"],
        "composers": ["Masaaki Iizuka"],
        "releaseDate": "2016-04-13",
        "startingEpisode": 1,
        "endingEpisode": 12,
        "openingNumber": 1,
        "songVideoLink": "https://www.youtube.com/watch?v=sDhgSZXPLdY",
        "fullSongLink": "https://www.youtube.com/watch?v=-e119C6VGHA"
    },
    {
        "id": "true-story",
        "type": "opening-theme",
        "name": "TRUE STORY",
        "artist": "SCREEN mode",
        "lyricists": ["Yōhei Matsui", "RUCCA"],
        "composers": ["Masatomo Ōta"],
        "releaseDate": "2023-01-25",
        "startingEpisode": 38,
        "endingEpisode": 50,
        "openingNumber": 4,
        "songVideoLink": "https://www.youtube.com/watch?v=ZT2T9hLwoV0",
        "fullSongLink": "https://www.youtube.com/watch?v=26w2Q1k0niw"
    },
    {
        "id": "bokura",
        "type": "ending-theme",
        "name": "Bokura",
        "artist": "Luck Life",
        "lyricists": ["PON"],
        "composers": ["PON"],
        "releaseDate": "2018-02-28",
        "startingEpisode": null,
        "endingEpisode": null,
        "endingNumber": null,
        "mediaId": "dead-apple-movie",
        "songVideoLink": null,
        "fullSongLink": "https://www.youtube.com/watch?v=8F2xbQJgHs4"
    },
    {
        "id": "kaze-ga-fuku-machi",
        "type": "ending-theme",
        "name": "Kaze ga Fuku Machi",
        "artist": "Luck Life",
        "lyricists": ["PON"],
        "composers": ["PON"],
        "releaseDate": "2016-11-13",
        "startingEpisode": 14,
        "endingEpisode": 24,
        "endingNumber": 2,
        "songVideoLink": "https://www.youtube.com/watch?v=YJkr6rSsdM0",
        "fullSongLink": "https://www.youtube.com/watch?v=vcJ61mfcK3A"
    },
    {
        "id": "kiseki",
        "type": "ending-theme",
        "name": "Kiseki",
        "artist": "Luck Life",
        "lyricists": ["PON"],
        "composers": ["PON"],
        "releaseDate": "2023-08-23",
        "startingEpisode": 51,
        "endingEpisode": 61,
        "endingNumber": 5,
        "songVideoLink": "https://www.youtube.com/watch?v=PFCSjQX0pdU",
        "fullSongLink": "https://www.youtube.com/watch?v=vuYs-1hVXlY"
    },
    {
        "id": "lily",
        "type": "ending-theme",
        "name": "Lily",
        "artist": "Luck Life",
        "lyricists": ["PON"],
        "composers": ["PON"],
        "releaseDate": "2019-05-08",
        "startingEpisode": 27,
        "endingEpisode": 37,
        "endingNumber": 3,
        "songVideoLink": "https://www.youtube.com/watch?v=ytuUjBqiBg0",
        "fullSongLink": "https://www.youtube.com/watch?v=bxbXUMy4kok"
    },
    {
        "id": "namae-wo-yobu-yo",
        "type": "ending-theme",
        "name": "Namae wo Yobu yo",
        "artist": "Luck Life",
        "lyricists": ["PON"],
        "composers": ["PON"],
        "releaseDate": "2016-05-11",
        "startingEpisode": 1,
        "endingEpisode": 12,
        "endingNumber": 1,
        "songVideoLink": "https://www.youtube.com/watch?v=LXlgpYBnXVY",
        "fullSongLink": "https://www.youtube.com/watch?v=-g6MYL5lOZs"
    },
    {
        "id": "shirushi",
        "type": "ending-theme",
        "name": "Shirushi",
        "artist": "Luck Life",
        "lyricists": ["PON"],
        "composers": ["PON"],
        "releaseDate": "2023-01-25",
        "startingEpisode": 38,
        "endingEpisode": 50,
        "endingNumber": 4,
        "songVideoLink": "https://www.youtube.com/watch?v=WO1lFTiWTPI",
        "fullSongLink": "https://www.youtube.com/watch?v=YbFSOlLemak"
    },
    {
        "id": "wright-left",
        "type": "insert-song",
        "name": "Wright Left",
        "artist": "SCREEN mode",
        "lyricists": ["Yōhei Matsui"],
        "composers": ["Masatomo Ōta"],
        "releaseDate": "2019-07-03",
        "startingEpisode": 37,
        "endingEpisode": 37,
        "songVideoLink": null,
        "fullSongLink": "https://www.youtube.com/watch?v=l3oYAk6hxX8"
    },
    {
        "id": "tokeimawari-no-torque",
        "type": "theme-song",
        "name": "Tokeimawari no Torque",
        "artist": "GRANRODEO",
        "lyricists": ["Kishō Taniyama"],
        "composers": ["Masaaki Iizuka"],
        "releaseDate": "2022-01-07",
        "mediaId": "beast-live-action",
        "songVideoLink": "https://www.youtube.com/watch?v=z9IIp7yT79s",
        "fullSongLink": "https://www.youtube.com/watch?v=x32LxeCiPKU"
    },
    {
        "id": "young-boy-run-under-the-moonlight",
        "type": "character-song",
        "name": "Young Boy, Run Under the Moonlight",
        "japaneseName": "少年よ月下を病走れ",
        "artist": "Yūto Uemura",
        "composers": ["Tsukasa Yatoki", "Takuya Sakai", "Atsushi Harada"],
        "releaseDate": "2016-08-17",
        "fullSongLink": "https://www.youtube.com/watch?v=ts_YzXIZQj4",
        "characterId": "atsushi-nakajima"
    },
    {
        "id": "goodbye-to-the-attempt-on-eternity",
        "type": "character-song",
        "name": "Goodbye to the Attempt on Eternity",
        "japaneseName": "永遠未遂にグッド・バイ",
        "artist": "Mamoru Miyano",
        "composers": ["Tsukasa Yatoki", "Takuya Sakai", "Atsushi Harada"],
        "releaseDate": "2016-08-17",
        "fullSongLink": "https://www.youtube.com/watch?v=GRNEVLsAiCE",
        "characterId": "osamu-dazai"
    },
    {
        "id": "unclouded-by-my-ideals",
        "type": "character-song",
        "name": "Unclouded by my Ideals",
        "japaneseName": "我が理想に曇り無し",
        "artist": "Yoshimasa Hosoya",
        "composers": ["Tsukasa Yatoki", "Takuya Sakai", "Atsushi Harada"],
        "releaseDate": "2016-08-17",
        "fullSongLink": "https://www.youtube.com/watch?v=zlr1UqkTe-g",
        "characterId": "doppo-kunikida"
    },
    {
        "id": "labyrinth-deciphering-game",
        "type": "character-song",
        "name": "Labyrinth Deciphering Game",
        "japaneseName": "迷宮解読遊戯",
        "artist": "Hiroshi Kamiya",
        "composers": ["Yuki Honda", "Atsushi Harada", "Masatomi Waki"],
        "releaseDate": "2016-09-14",
        "fullSongLink": "https://www.youtube.com/watch?v=OA-napHUG30",
        "characterId": "ranpo-edogawa"
    },
    {
        "id": "the-way-of-honest-people",
        "type": "character-song",
        "name": "The Way of Honest People",
        "japaneseName": "正直者ノ流儀",
        "artist": "Hiroyuki Kagura",
        "composers": ["Yuki Honda", "Atsushi Harada", "Masatomi Waki"],
        "releaseDate": "2016-09-14",
        "fullSongLink": "https://www.youtube.com/watch?v=gkV4WkgwmYk",
        "characterId": "kenji-miyazawa"
    },
    {
        "id": "bewitching-screens",
        "type": "character-song",
        "name": "Bewitching Screens",
        "japaneseName": "幻惑のスクリィン",
        "artist": "Toshiyuki Toyonaga",
        "composers": ["Yuki Honda", "Atsushi Harada", "Masatomi Waki"],
        "releaseDate": "2016-09-14",
        "fullSongLink": "https://www.youtube.com/watch?v=v4SS3rXfncI",
        "characterId": "junichiro-tanizaki"
    },
    {
        "id": "from-the-trembling-dark-world",
        "type": "character-song",
        "name": "From the Trembling Dark World",
        "japaneseName": "揺らぐ暗澹の世界から",
        "artist": "Kenshō Ono",
        "composers": ["Yuki Honda"],
        "releaseDate": "2016-10-05",
        "fullSongLink": "https://www.youtube.com/watch?v=kGsTmnpm-GE",
        "characterId": "ryunosuke-akutagawa"
    },
    {
        "id": "darkness-my-sorrow",
        "type": "character-song",
        "name": "DARKNESS MY SORROW",
