=== Nekopawa/bsd-explorer/schemas/soundtrack.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/Nekopawa/bsd-explorer/main/schemas/soundtrack.schema.json",
    "title": "Soundtrack",
    "description": "Soundtrack used in the anime - original and Wan!",
    "type": "array",
    "items": {
        "type": "object",
        "description": "Soundtrack used in the anime - original and Wan!",
        "properties": {
            "id": {
                "type": "string",
                "description": "ID of the soundtrack.",
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                "minLength": 1
            },
            "name": {
                "type": "string",
                "description": "Name of the soundtrack.",
                "minLength": 1
            },
            "composers": {
                "type": "array",
                "description": "Composers involved in the soundtrack.",
                "items": {
                    "type": "string",
                    "description": "The name of the composer.",
                    "minLength": 1
                },
                "minItems": 1
            },
            "releaseDate": {
                "type": "string",
                "description": "The release date of the soundtrack.",
                "format": "date",
                "minLength": 1
            },
            "mediaId": {
                "type": "string",
                "description": "The ID of the media that features the soundtrack.",
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                "minLength": 1
            },
            "seasons": {
                "type": ["array", "null"],
                "description": "The seasons that feature the soundtrack.",
                "items": {
                    "type": "integer",
                    "description": "The number of the season.",
                    "minimum": 1
                },
                "minItems": 1
            },
            "tracks": {
                "type": "array",
                "description": "The tracks featured in the soundtrack.",
                "items": {
                    "type": "object",
                    "description": "The track featured in the soundtrack.",
                    "properties": {
                        "number": {
                            "type": "integer",
                            "description": "The number of the track.",
                            "minimum": 1
                        },
                        "name": {
                            "type": "string",
                            "description": "The name of the track.",
                            "minLength": 1
                        },
                        "japaneseName": {
                            "type": ["string", "null"],
                            "description": "The japanese name of the track.",
                            "minLength": 1
                        },
                        "musicId": {
                            "type": ["string", "null"],
                            "description": "The ID of the corresponding song in music.json.",
                            "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
                        },
                        "disc": {
                            "type": ["integer", "null"],
                            "description": "The number of the disc that features the track.",
                            "minimum": 1
                        }
                    },
                    "required": ["number", "name", "japaneseName"],
                    "additionalProperties": false
                },
                "minItems": 1
            }
        },
        "required": [
            "id",
            "name",
            "composers",
            "releaseDate",
            "mediaId",
            "seasons",
            "tracks"
        ],
        "additionalProperties": false
    }
}

=== Nekopawa/bsd-explorer/src/data/soundtrack.json
[
    {
        "id": "bsd-original-soundtrack-1",
        "name": "Bungo Stray Dogs Original Soundtrack 1",
        "composers": ["Taku Iwasaki", "Masaaki Iizuka", "PON"],
        "releaseDate": "2016-07-29",
        "mediaId": "bsd-anime",
        "seasons": [1],
        "tracks": [
            {
                "number": 1,
                "name": "Good For Nothing",
                "japaneseName": null
            },
            {
                "number": 2,
                "name": "Otoko to Onna",
                "japaneseName": "男と女"
            },
            {
                "number": 3,
                "name": "Ochazuke Don!",
                "japaneseName": "御茶漬ドン!"
            },
            {
                "number": 4,
                "name": "Haji no Ōi Shōgai wo,,!",
                "japaneseName": "恥の多い生涯を、、"
            },
            {
                "number": 5,
                "name": "Shikkaku",
                "japaneseName": "失格"
            },
            {
                "number": 6,
                "name": "Sore wa Hajimatte Iru",
                "japaneseName": "それは始まっている"
            },
            {
                "number": 7,
                "name": "Inō no Susume",
                "japaneseName": "異能ノススメ"
            },
            {
                "number": 8,
                "name": "Edogawa Kitan",
                "japaneseName": "江戸川奇譚"
            },
            {
                "number": 9,
                "name": "Spider Web",
                "japaneseName": null
            },
            {
                "number": 10,
                "name": "River Side Mafia",
                "japaneseName": null
            },
            {
                "number": 11,
                "name": "Furachi",
                "japaneseName": "不埒"
            },
            {
                "number": 12,
                "name": "Hashire Atsushi!",
                "japaneseName": "走れ敦!"
            },
            {
                "number": 13,
                "name": "Kimi Shinitamō Koto Nakare",
                "japaneseName": "君死にたまふことなかれ"
            },
            {
                "number": 14,
                "name": "Kore wa Koi?",
                "japaneseName": "これは恋?"
            },
            {
                "number": 15,
                "name": "Fujō",
                "japaneseName": "不浄"
            },
            {
                "number": 16,
                "name": "Rashōmon",
                "japaneseName": "羅生門"
            },
            {
                "number": 17,
                "name": "Leaping Wings",
                "japaneseName": null
            },
            {
                "number": 18,
                "name": "Kokoro Furueker",
                "japaneseName": "こころ ふるえけり"
            },
            {
                "number": 19,
                "name": "Eye Of The Tiger",
                "japaneseName": null
            },
            {
                "number": 20,
                "name": "Busō Tantei-sha",
                "japaneseName": "武装探偵社"
            },
            {
                "number": 21,
                "name": "TRASH CANDY",
                "japaneseName": null,
                "musicId": "trash-candy"
            },
            {
                "number": 22,
                "name": "Namae wo Yobu yo",
                "japaneseName": "名前を呼ぶよ",
                "musicId": "namae-wo-yobu-yo"
            }
        ]
    },
    {
        "id": "bsd-original-soundtrack-2",
        "name": "Bungo Stray Dogs Original Soundtrack 2",
        "composers": ["Taku Iwasaki", "Masatomo Ōta", "PON"],
        "releaseDate": "2016-12-28",
        "mediaId": "bsd-anime",
        "seasons": [2],
        "tracks": [
            {
                "number": 1,
                "name": "Scarlet Sky",
                "japaneseName": null
            },
            {
                "number": 2,
                "name": "Kyōchikutō",
                "japaneseName": "夾竹桃"
            },
            {
                "number": 3,
                "name": "Dormito Bene",
                "japaneseName": null
            },
            {
                "number": 4,
                "name": "Shōbi",
                "japaneseName": "焦眉"
            },
            {
                "number": 5,
                "name": "Bungō AcidJazz",
                "japaneseName": "文豪AcidJazz"
            },
            {
                "number": 6,
                "name": "Utsu Nikki",
                "japaneseName": "鬱日記"
            },
            {
                "number": 7,
                "name": "Shūbi",
                "japaneseName": "愁眉"
            },
            {
                "number": 8,
                "name": "Shin'en",
                "japaneseName": "深淵"
            },
            {
                "number": 9,
                "name": "Aa Erisu",
                "japaneseName": "嗚呼ヱリス"
            },
            {
                "number": 10,
                "name": "Aru Q",
                "japaneseName": "或Q"
            },
            {
                "number": 11,
                "name": "Musashino Maach",
                "japaneseName": "武蔵野マアチ"
            },
            {
                "number": 12,
                "name": "Bungō Rokku 645",
                "japaneseName": "文豪ロック645"
            },
            {
                "number": 13,
                "name": "Batalha",
                "japaneseName": null
            },
            {
                "number": 14,
                "name": "Kante",
                "japaneseName": null
            },
            {
                "number": 15,
                "name": "Ai to Gikō",
                "japaneseName": "愛と技巧"
            },
            {
                "number": 16,
                "name": "Ojoku",
                "japaneseName": null
            },
            {
                "number": 17,
                "name": "Bungō Kōkyōkyoku Dai 1-ban 1 Gakushō Kumiai",
                "japaneseName": "文豪交響曲第1番 1楽章 組合"
            },
            {
                "number": 18,
                "name": "Bungō Kōkyōkyoku Dai 1-ban 2 Gakushō Kujira",
                "japaneseName": "文豪交響曲第1番 2楽章 鯨"
            },
            {
                "number": 19,
                "name": "Bungō Kōkyōkyoku Dai 1-ban 3 Gakushō Yokohama",
                "japaneseName": "文豪交響曲第1番 3楽章 横浜"
            },
            {
                "number": 20,
                "name": "Tomo to Iu Mono",
                "japaneseName": "友といふもの"
            },
            {
                "number": 21,
                "name": "Reason Living",
                "japaneseName": null,
                "musicId": "reason-living"
            },
            {
                "number": 22,
                "name": "Kaze ga Fuku Machi",
                "japaneseName": null,
                "musicId": "kaze-ga-fuku-machi"
            }
        ]
    },
    {
        "id": "bsd-original-soundtrack-3",
        "name": "Bungo Stray Dogs Original Soundtrack 3",
        "composers": ["Taku Iwasaki", "Masaaki Iizuka", "PON"],
        "releaseDate": "2019-07-31",
        "mediaId": "bsd-anime",
        "seasons": [3],
        "tracks": [
            {
                "number": 1,
                "name": "Violette Irise",
                "japaneseName": null
            },
            {
                "number": 2,
                "name": "Arahabaki",
                "japaneseName": "アラハバキ"
            },
            {
                "number": 3,
                "name": "Randō to Iu Otoko Sono Ichi",
                "japaneseName": "蘭堂と云フ男 其の一"
            },
            {
                "number": 4,
                "name": "Yokohama Urei,,",
                "japaneseName": "横浜憂ヒ、、"
            },
            {
                "number": 5,
                "name": "Randō to Iu Otoko Sono Ni",
                "japaneseName": "蘭堂と云フ男 其の二"
            },
            {
                "number": 6,
                "name": "Honoka ni",
                "japaneseName": "仄かに"
            },
            {
                "number": 7,
                "name": "Ulmoi",
                "japaneseName": null
            },
            {
                "number": 8,
                "name": "Mōsō Tengoku",
                "japaneseName": "妄想天国"
            },
            {
                "number": 9,
                "name": "Tsuiraku-en",
                "japaneseName": "墜落園"
            },
            {
                "number": 10,
                "name": "Gōman to Chikara",
                "japaneseName": "傲慢と力"
            },
            {
                "number": 11,
                "name": "Tei Gen de Zugo",
                "japaneseName": "低弦でズゴッ"
            },
            {
                "number": 12,
                "name": "Chero to Piano no Tame no \"Shi no Tori\"",
                "japaneseName": "チェロとピアノの為の「死の鳥」"
            },
            {
                "number": 13,
                "name": "Gengaku Ōkesutora to Hāpu no Tame no \"Shi no Tori\"",
                "japaneseName": "弦楽オーケストラとハープの為の「死の鳥」"
            },
            {
                "number": 14,
                "name": "Teinen",
                "japaneseName": "諦念"
            },
            {
                "number": 15,
                "name": "Wagahai wa Nuko dearu",
                "japaneseName": "我輩はヌコである"
            },
            {
                "number": 16,
                "name": "Mikao to Tāpi",
                "japaneseName": "ミカオとターピ"
            },
            {
                "number": 17,
